development: &pgsql
  adapter: postgresql
  database: msf_main_db
  username: msf_max
  password: z0vSfC8MOmNjP7FuTyzJ7dg7Jw3Jg0JVracG8aRo36I=
  host: 127.0.0.1
  port: 5432
  pool: 200

production: &production
  <<: *pgsql

test:
  <<: *pgsql
  database: msftest
  username: msftest
  password: gNiUPLRd1+j/sLobhXiohtd258X7g8MLYHs8jvrepNM=
